# yaml-language-server: $schema=https://activate.parallel.works/workflow.schema.json
---
# Desktop - Interactive remote desktop session workflow
# Supports TigerVNC, TurboVNC, KasmVNC, and Singularity containers

permissions:
  - "*"

sessions:
  session:
    useTLS: false
    redirect: true # VNC uses redirect with custom slug for autoconnect

jobs:
  # =============================================================================
  # PREPROCESSING
  # =============================================================================
  preprocessing:
    steps:
      - name: Checkout service scripts
        uses: parallelworks/checkout
        ssh:
          remoteHost: ${{ inputs.resource.ip }}
        with:
          repo: https://github.com/parallelworks/activate-sessions.git
          branch: main
          sparse_checkout:
            - workflows/${{ inputs.workflow_dir }}

      - name: Transfer inputs from user workspace
        run: |
          set -e
          REMOTE_JOB_DIR="./pw/jobs/${PW_WORKFLOW_NAME}/${PW_JOB_NUMBER}/"
          if [ -f inputs.sh ]; then
            scp inputs.sh ${{ inputs.resource.ip }}:${REMOTE_JOB_DIR}
          fi

      - name: Run controller setup
        ssh:
          remoteHost: ${{ inputs.resource.ip }}
        run: |
          set -e
          cd workflows/${{ inputs.workflow_dir }}
          export PW_SESSION_NAME="${{ sessions.session }}"
          bash setup.sh

  # =============================================================================
  # SESSION RUNNER - runs start.sh on compute node
  # =============================================================================
  session_runner:
    needs: [preprocessing]
    ssh:
      remoteHost: ${{ inputs.resource.ip }}
    steps:
      # Submit start.sh to compute node
      - name: Submit session script
        early-cancel: any-job-failed
        uses: marketplace/job_runner/v4.0
        with:
          resource: ${{ inputs.resource }}
          rundir: "${PW_PARENT_JOB_DIR}"
          scheduler: ${{ inputs.submit_to_scheduler }}
          inject_markers: true
          slurm:
            is_disabled: ${{ inputs.submit_to_scheduler != true || inputs.resource.schedulerType != 'slurm' }}
            account: ${{ inputs.slurm.account }}
            partition: ${{ inputs.slurm.partition }}
            qos: ${{ inputs.slurm.qos }}
            time: ${{ inputs.slurm.time }}
            cpus_per_task: ${{ inputs.slurm.cpus_per_task }}
            gres: ${{ inputs.slurm.gres }}
            scheduler_directives: |
              ${{ inputs.slurm.scheduler_directives }}
          pbs:
            is_disabled: ${{ inputs.submit_to_scheduler != true || inputs.resource.schedulerType != 'pbs' }}
            account: ${{ inputs.pbs.account }}
            queue: ${{ inputs.pbs.queue }}
            walltime: ${{ inputs.pbs.walltime }}
            select: ${{ inputs.pbs.select }}
            scheduler_directives: |
              ${{ inputs.pbs.scheduler_directives }}
          use_existing_script: true
          script_path: "${PW_PARENT_JOB_DIR}/workflows/${{ inputs.workflow_dir }}/start.sh"

      - name: Notify job ended
        early-cancel: any-job-failed
        run: touch job.ended

  # ==============================================================================
  # WAIT FOR SERVICE - wait for job to start and get connection info
  # ==============================================================================
  wait_for_service:
    needs: [preprocessing]
    ssh:
      remoteHost: ${{ inputs.resource.ip }}
    steps:
      - name: Wait for desktop ready
        early-cancel: any-job-failed
        run: |
          # Wait for job to start
          while [ ! -f job.started ]; do
            [ -f job.ended ] && echo "ERROR: Job ended before starting" && exit 1
            sleep 3
          done

          # Read connection info (with NFS cache refresh)
          sleep 2 && ls -la . >/dev/null 2>&1
          HOSTNAME=$(cat HOSTNAME)
          SESSION_PORT=$(cat SESSION_PORT)

          # Wait for service to respond
          for i in $(seq 1 100); do
            if curl -s --connect-timeout 5 --max-time 5 "http://${HOSTNAME}:${SESSION_PORT}" -o /dev/null 2>&1; then
              echo "HOSTNAME=${HOSTNAME}" >> $OUTPUTS
              echo "SESSION_PORT=${SESSION_PORT}" >> $OUTPUTS
              exit 0
            fi
            [ -f job.ended ] && echo "ERROR: Job ended" && exit 1
            sleep 3
          done
          echo "ERROR: Service timeout" && exit 1

  # =============================================================================
  # UPDATE SESSION - configure session proxy with custom slug
  # =============================================================================
  update_session:
    needs: [preprocessing, wait_for_service]
    ssh:
      remoteHost: ${{ inputs.resource.ip }}
    steps:
      - name: Get local port
        run: |
          local_port=$(pw agent open-port)
          echo "local_port=${local_port}" | tee -a $OUTPUTS

      - name: Update session with custom slug
        uses: parallelworks/update-session
        with:
          target: ${{ inputs.resource.id }}
          name: ${{ sessions.session }}
          slug: ${{ needs.preprocessing.outputs.slug }}
          remoteHost: ${{ needs.wait_for_service.outputs.HOSTNAME }}
          remotePort: ${{ needs.wait_for_service.outputs.SESSION_PORT }}
          local_port: ${{ needs.update_session.outputs.local_port }}

  # =============================================================================
  # COMPLETE - print connection info
  # =============================================================================
  complete:
    needs: [update_session]
    steps:
      - name: Display connection info
        run: |
          basepath="/me/session/${PW_USER}/${{ sessions.session }}"
          echo "=========================================="
          echo "Desktop Session is ready!"
          echo "=========================================="
          echo "  Connect via: ${PW_PLATFORM_HOST}${basepath}/"
          echo "=========================================="

"on":
  execute:
    inputs:
      resource:
        type: compute-clusters
        label: Service host
        include-workspace: false
        autoselect: true

      workflow_dir:
        type: string
        default: desktop
        hidden: true

      submit_to_scheduler:
        type: boolean
        label: Submit to Job Scheduler
        tooltip: Enable to submit job via SLURM or PBS scheduler (detected automatically from resource). Disable for direct SSH execution.
        default: false
        hidden: ${{ inputs.resource.schedulerType != 'slurm' && inputs.resource.schedulerType != 'pbs' }}

      slurm:
        type: group
        label: SLURM Configuration
        hidden: ${{ inputs.submit_to_scheduler != true || inputs.resource.schedulerType != 'slurm' }}
        collapsed: true
        items:
          is_disabled:
            type: boolean
            default: ${{ inputs.submit_to_scheduler != true || inputs.resource.schedulerType != 'slurm' }}
            hidden: true

          account:
            label: Account
            type: slurm-accounts
            resource: ${{ inputs.resource }}
            tooltip: SLURM account for job submission (--account)
            optional: true
            ignore: ${{ inputs.submit_to_scheduler != true || inputs.resource.schedulerType != 'slurm' }}

          partition:
            type: slurm-partitions
            label: Partition
            optional: true
            resource: ${{ inputs.resource }}
            tooltip: Partition for job submission (--partition)
            ignore: ${{ inputs.submit_to_scheduler != true || inputs.resource.schedulerType != 'slurm' }}

          qos:
            label: Quality of Service (QoS)
            type: slurm-qos
            resource: ${{ inputs.resource }}
            tooltip: SLURM QoS setting (--qos)
            optional: true
            ignore: ${{ inputs.submit_to_scheduler != true || inputs.resource.schedulerType != 'slurm' }}

          cpus_per_task:
            type: number
            label: CPUs per Task
            min: 1
            max: 256
            default: 1
            tooltip: Number of CPUs for the job (--cpus-per-task)
            ignore: ${{ inputs.submit_to_scheduler != true || inputs.resource.schedulerType != 'slurm' }}

          time:
            label: Walltime
            type: string
            default: 04:00:00
            tooltip: Maximum job duration, e.g., 04:00:00 (--time)
            ignore: ${{ inputs.submit_to_scheduler != true || inputs.resource.schedulerType != 'slurm' }}

          gres:
            label: GPUs (gres)
            type: dropdown
            default: ""
            optional: true
            tooltip: GPU resource specification (--gres). Leave empty for CPU-only jobs.
            options:
              - value: ""
                label: "No GPU (CPU only)"
              - value: "gpu:1"
                label: "1 GPU (gpu:1)"
              - value: "gpu:2"
                label: "2 GPUs (gpu:2)"
              - value: "gpu:4"
                label: "4 GPUs (gpu:4)"
              - value: "gpu:8"
                label: "8 GPUs (gpu:8)"
            ignore: ${{ inputs.submit_to_scheduler != true || inputs.resource.schedulerType != 'slurm' }}

          scheduler_directives:
            type: editor
            label: Additional Directives
            optional: true
            tooltip: Additional SLURM directives (include #SBATCH prefix)
            ignore: ${{ inputs.submit_to_scheduler != true || inputs.resource.schedulerType != 'slurm' }}

      pbs:
        type: group
        label: PBS Configuration
        hidden: ${{ inputs.submit_to_scheduler != true || inputs.resource.schedulerType != 'pbs' }}
        collapsed: true
        items:
          is_disabled:
            type: boolean
            default: ${{ inputs.submit_to_scheduler != true || inputs.resource.schedulerType != 'pbs' }}
            hidden: true

          account:
            label: Account
            type: string
            optional: true
            tooltip: PBS account for job submission (-A)
            ignore: ${{ inputs.submit_to_scheduler != true || inputs.resource.schedulerType != 'pbs' }}

          queue:
            label: Queue
            type: string
            optional: true
            tooltip: PBS queue name (-q)
            ignore: ${{ inputs.submit_to_scheduler != true || inputs.resource.schedulerType != 'pbs' }}

          walltime:
            label: Walltime
            type: string
            default: 04:00:00
            tooltip: Maximum job duration, e.g., 04:00:00 (-l walltime=)
            ignore: ${{ inputs.submit_to_scheduler != true || inputs.resource.schedulerType != 'pbs' }}

          select:
            label: Resource Selection
            type: string
            default: "1:ncpus=8:ngpus=1"
            placeholder: "1:ncpus=8:ngpus=1"
            tooltip: PBS resource selection string, e.g., 1:ncpus=8:ngpus=1 (-l select=)
            ignore: ${{ inputs.submit_to_scheduler != true || inputs.resource.schedulerType != 'pbs' }}

          scheduler_directives:
            label: Additional Directives
            type: editor
            tooltip: Additional PBS directives (include #PBS prefix)
            optional: true
            ignore: ${{ inputs.submit_to_scheduler != true || inputs.resource.schedulerType != 'pbs' }}

      desktop:
        type: group
        label: Desktop Settings
        items:
          environment:
            type: dropdown
            label: Desktop Environment
            default: auto
            options:
              - label: Auto-detect
                value: auto
              - label: GNOME
                value: gnome
              - label: XFCE
                value: xfce
              - label: MATE
                value: mate
              - label: Cinnamon
                value: cinnamon
              - label: KDE Plasma
                value: kde
              - label: LXDE
                value: lxde
